# Generated by Django 2.0.7 on 2018-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='f', max_length=1),
        ),
    ]
